name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
    paths:
      - apps/algorithms/src/**

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd apps/algorithms
          npm install

      - name: Build with Next.js
        run: |
          cd apps/algorithms
          npm run build

      - name: Archive artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/algorithms/.next  # Certifique-se de que esse caminho está correto

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
