name: Deploy Next.js to Vercel

on:
  push:
    branches:
      - main  # Ou qualquer outro branch que você deseja que dispare o deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd apps/algorithms
          npm install

      - name: Build the project
        run: |
          cd apps/algorithms
          npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} --scope your-vercel-scope --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
