name: Preview Deployment - Website

on:
  push:
    branches-ignore:
      - main
    paths:
      - apps/algorithms/**  # Ajuste o caminho conforme necessário
      - packages/**  # Inclua outros caminhos relevantes para mudanças

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd apps/algorithms
          npm install

      - name: Build the project
        run: |
          cd apps/algorithms
          npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prebuilt --archive=tgz
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
